### ISSUE TITLE
DbCallback_InsertDeath - ttt_rdm

### ISSUE THREAD

**Issue by Septembers** [TroubleInTerroristTown/Public#480]
I tried to recreate the database - the error persisted. Database - MySQL

L 08/23/2020 - 10:03:25: [ttt/ttt_rdm.smx] DbCallback_InsertDeath: Out of range value for column 'victim_id' at row 1
L 08/23/2020 - 10:04:35: [ttt/ttt_rdm.smx] DbCallback_InsertDeath: Out of range value for column 'attacker_id' at row 1
L 08/23/2020 - 10:06:51: [ttt/ttt_rdm.smx] DbCallback_InsertDeath: Out of range value for column 'victim_id' at row 1
L 08/23/2020 - 10:06:52: [ttt/ttt_rdm.smx] DbCallback_InsertDeath: Out of range value for column 'attacker_id' at row 1
L 08/23/2020 - 10:07:50: [ttt/ttt_rdm.smx] DbCallback_InsertDeath: Out of range value for column 'victim_id' at row 1
L 08/23/2020 - 10:08:01: [ttt/ttt_rdm.smx] DbCallback_InsertDeath: Out of range value for column 'attacker_id' at row 1
L 08/23/2020 - 10:08:43: [ttt/ttt_rdm.smx] DbCallback_InsertDeath: Out of range value for column 'victim_id' at row 1
L 08/23/2020 - 10:11:24: [ttt/ttt_rdm.smx] DbCallback_InsertDeath: Out of range value for column 'victim_id' at row 1
L 08/23/2020 - 10:12:57: [ttt/ttt_rdm.smx] DbCallback_InsertDeath: Out of range value for column 'attacker_id' at row 1
L 08/23/2020 - 10:13:08: [ttt/ttt_rdm.smx] DbCallback_InsertDeath: Out of range value for column 'victim_id' at row 1
L 08/23/2020 - 10:14:31: [ttt/ttt_rdm.smx] DbCallback_InsertDeath: Out of range value for column 'victim_id' at row 1
L 08/23/2020 - 10:14:34: [ttt/ttt_rdm.smx] DbCallback_InsertDeath: Out of range value for column 'victim_id' at row 1
L 08/23/2020 - 10:16:00: [ttt/ttt_rdm.smx] DbCallback_InsertDeath: Out of range value for column 'victim_id' at row 1
L 08/23/2020 - 10:16:42: [ttt/ttt_rdm.smx] DbCallback_InsertDeath: Out of range value for column 'victim_id' at row 1

MetaMod Version (meta version): Metamod:Source version 1.11.0-dev+1131
SourceMod Version (sm version): SourceMod Version: 1.10.0.6492
TTT Version (sm_tttversion): TTT Version: 2231 (as string: 1.10.2231.be987499)

**Comment by Bara** [comment]
@c0rp3n your plugin ;)

**Comment by c0rp3n** [comment]
Shall take a look after work :)

**Comment by Septembers** [comment]
@c0rp3n Thanks, we're waiting

**Comment by c0rp3n** [comment]
So I've tried to look into this, could you try validating that your `ttt` table in your database does not have any id's of `-1` not sure how or why but could a cause.

Made some changes to try fix this but not been able to replicate this yet.
The error usually means that the value passed is out of range meaning `victim_id` or `attacker_id` are negative as the value is meant to be an unsigned integer.

See the new pull requests for the changes, if you need a precompiled version of ttt_rdm to try just let me know.
