### ISSUE TITLE
Deathstation does not log damage

### ISSUE THREAD

**Issue by millerze** [TroubleInTerroristTown/Public#491]
It confuses players because it's mystery damage.  Just need to send the damage to logs.

        if (g_iPlayer[owner].Type == Hurt)
        {
            iNewHealth = iCurrentHealth - g_cHurtDamage.IntValue;
			TTT_LogString("-> [%N's death station damaged %N for 25 damage.]", owner, client);
        }
Something like that I suppose

**Comment by millerze** [comment]
Same with decoy bodies.  Do not register damage in log

**Comment by Bara** [comment]
I've added this into our beta branch and will pushed into the public branch within the next update.

**Comment by Bara** [comment]
https://github.com/TroubleInTerroristTown/Public/blob/master/changelogs/2021-01.md
