### ISSUE TITLE
Using the player_ping command opens sm_shop

### ISSUE THREAD

**Issue by Owkoot** [TroubleInTerroristTown/Public#495]
With the new operation being out, it might be useful to remove this feature, as it gets in the way of using player_ping on TTT servers. 😄

**Comment by LubricantJam** [comment]
Turn it off, it's not really needed for community servers.

**Comment by Bara** [comment]
I've added this into our beta branch and will pushed into the public branch within the next update.

**Comment by Bara** [comment]
https://github.com/TroubleInTerroristTown/Public/blob/master/changelogs/2021-01.md
