### ISSUE TITLE
Handle is invalid [ttt_haste]

### ISSUE THREAD

**Issue by Septembers** [TroubleInTerroristTown/Public#505]
Greetings. Reporting an error in the logs

L 01/31/2022 - 13:19:35: [SM] Exception reported: Handle d6a110d0 is invalid (error 1)
L 01/31/2022 - 13:19:35: [SM] Blaming: ttt/ttt_haste.smx
L 01/31/2022 - 13:19:35: [SM] Call stack trace:
L 01/31/2022 - 13:19:35: [SM]   [0] CloseHandle
L 01/31/2022 - 13:19:35: [SM]   [1] Line 159, ttt_haste.sp::StartHasteRound
L 01/31/2022 - 13:19:35: [SM]   [2] Line 91, ttt_haste.sp::TTT_OnRoundStart
L 01/31/2022 - 13:19:35: [SM]   [4] Call_Finish
L 01/31/2022 - 13:19:35: [SM]   [5] Line 217, core/sql.sp::SQL_InsertRound
L 01/31/2022 - 13:20:51: [SM] Exception reported: Invalid timer handle d6a110d0 (error 1)
L 01/31/2022 - 13:20:51: [SM] Blaming: ttt/ttt_haste.smx
L 01/31/2022 - 13:20:51: [SM] Call stack trace:
L 01/31/2022 - 13:20:51: [SM]   [0] KillTimer
L 01/31/2022 - 13:20:51: [SM]   [1] Line 876, /home/runner/work/Public/Public/addons/sourcemod/scripting/include/ttt.inc::TTT_ClearTimer
L 01/31/2022 - 13:20:51: [SM]   [2] Line 97, ttt_haste.sp::TTT_OnRoundEnd
L 01/31/2022 - 13:20:51: [SM]   [4] Call_Finish
L 01/31/2022 - 13:20:51: [SM]   [5] Line 3759, ttt.sp::CS_OnTerminateRound
L 01/31/2022 - 13:20:51: [SM]   [7] CS_TerminateRound
L 01/31/2022 - 13:20:51: [SM]   [8] Line 4741, ttt.sp::CheckTeams
L 01/31/2022 - 13:20:51: [SM]   [9] Line 3603, ttt.sp::Event_PlayerDeath

## Server Details
Please provide us some details and specifications of the server you've encountered the bug on. This helps us narrow down specific issues as not all bugs are blanketed over multiple versions of SourceMod, MetaMod, etc.

- **MetaMod Version (meta version):** Metamod:Source version 1.11.0-dev+1145
- **SourceMod Version (sm version):** SourceMod Version: 1.10.0.6521
- **TTT Version (sm_tttversion):** TTT Version: 2262 (as string: 1.10.2262.5d793b6e)

**Comment by Bara** [comment]
I'm aware of this issue. In some cases `delete` will throw this error for some reasons, which I can't really reproduce in last tests.
